name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/inessoler11/AnálisisPostura
          cd Análisis Postura
          cp -r ../* .
          git add .
          git commit -m "Actualizando Space desde GitHub"
          git push
